@startuml
left to right direction

actor Cashier <<Person>>

rectangle Building {
  actor MotionSensor <<Equipment>>
  usecase DetectMotion
  usecase Monitoring [
    Monitoring
    ---
    Extension Point: viewCCTV
  ]
  rectangle VendingMachine {
  }
}
Cashier --> Monitoring : "{over Internet}"
MotionSensor --> DetectMotion
DetectMotion ..> Monitoring : <<extends>> {if detected}
@enduml
