@startuml

interface Stack {
  + push(obj: Element)
  + pop(): Element
  + reset()
  {static} + createNew(): Stack
}

class ListStack {
  + push(obj: Element)
  + pop(): Element
  + reset()
  {static} + createNew(): Stack
}

Stack <|.. ListStack

@enduml
