@startuml
class SmartHouse {
    -wall[4] : Wall
    -roof : Roof
    +stormWarning()
    +harden()
    +closeWindows()
}

class Wall {
}

class Roof {
}

class Material {
    +price: double
    +unitWeight: double
}

SmartHouse --o Wall
SmartHouse --o Roof

@enduml
