@startuml
left to right direction

actor Cashier
actor Loader
rectangle VendingMachine {
    usecase CollectCash
    usecase ChangeWater
    usecase ChangeGas
}

Cashier --> CollectCash
Loader --> ChangeWater
Loader --> ChangeGas
@enduml
