@startuml
left to right direction

actor Loader

rectangle VendingMachine {
    usecase ChangeSyrup
    usecase Maintenance

}

Loader --> ChangeSyrup
ChangeSyrup --> Maintenance: <<exclude>>
@enduml
