@startuml
entity "Services" {
    * service_id : SERIAL [PK]
    * service_name : VARCHAR(255) [UNIQUE]
    * created_at : TIMESTAMP
    * schema_id: INT [FK]
}

entity "Schemas" {
    * schema_id : SERIAL [PK]
    * service_id : INT [FK]
    * json_schema : JSON
    * created_at : TIMESTAMP
    * version: INT
}

Services ||--o{ Schemas
@enduml
