@startuml
entity "Services" {
    * service_id : SERIAL [PK]
    * name : VARCHAR(255) [UNIQUE]
    * docker_image : VARCHAR(255)
    * replicas : INT
    * created_at : TIMESTAMP
    * updated_at : TIMESTAMP
}

entity "Schemas" {
    * schema_id : SERIAL [PK]
    * service_id : INT [FK]
    * json_schema : JSON
}

Services ||--o{ Schemas
@enduml
