@startuml
entity "Models" {
    * model_id : SERIAL [PK]
    * model_name : VARCHAR(255)
    * description : TEXT
}

entity "Routes" {
    * route_id : SERIAL [PK]
    * model_id : INT [FK]
    * dns : VARCHAR(255)
    * params : TEXT
}

entity "Load Balancers" as LoadBalancers {
    * lb_id : SERIAL [PK]
    * model_id : INT [FK]
    * server_weights : JSON
}

entity "Schemas" {
    * schema_id : SERIAL [PK]
    * model_id : INT [FK]
    * json_schema : JSON
}

Models ||--o{ Routes : "1-to-many"
Models ||--o{ LoadBalancers : "1-to-many"
Models ||--o{ Schemas : "1-to-many"
@enduml
