apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requestrouters.example.com
spec:
  group: example.com
  names:
    kind: RequestRouter
    listKind: RequestRouterList
    plural: requestrouters
    singular: requestrouter
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      dns:
                        type: string
                      serviceName:
                        type: string
                      params:
                        type: string
                loadBalancers:
                  type: array
                  items:
                    type: object
                    properties:
                      modelId:
                        type: string
                      serverWeights:
                        type: object
                        additionalProperties:
                          type: integer
                schemas:
                  type: array
                  items:
                    type: object
                    properties:
                      modelId:
                        type: string
                      jsonSchema:
                        type: object
