apiVersion: v1
kind: ConfigMap
metadata:
  name: request-router-config
data:
  cache_url: "redis://router-cache:6379"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-router
spec:
  replicas: 3
  selector:
    matchLabels:
      app: request-router
  template:
    metadata:
      labels:
        app: request-router
    spec:
      containers:
      - name: request-router
        image: request-router:latest
        env:
        - name: CACHE_URL
          valueFrom:
            configMapKeyRef:
              name: request-router-config
              key: cache_url
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: request-router
spec:
  selector:
    app: request-router
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
