@startuml
entity "Services" {
    * service_id : SERIAL [PK]
    * name : VARCHAR(255) [UNIQUE]
    * docker_image : VARCHAR(255)
    * replicas : INT
    * created_at : TIMESTAMP
    * updated_at : TIMESTAMP
}

entity "Routes" {
    * route_id : SERIAL [PK]
    * service_id : INT [FK]
    * dns : VARCHAR(255)
    * params : TEXT
}

entity "Load Balancers" as LoadBalancers {
    * lb_id : SERIAL [PK]
    * service_id : INT [FK]
    * params : TEXT
}

entity "Schemas" {
    * schema_id : SERIAL [PK]
    * service_id : INT [FK]
    * json_schema : JSON
}

Services ||--o{ Routes
Services ||--o{ LoadBalancers
Services ||--o{ Schemas
@enduml