apiVersion: v1
kind: ConfigMap
metadata:
  name: service-deployer-config
data:
  database_url: "postgresql://deploy_user:password@deployer-db/service_deployer"

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-deployer
  template:
    metadata:
      labels:
        app: service-deployer
    spec:
      containers:
      - name: service-deployer
        image: service-deployer:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: service-deployer-config
              key: database_url
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: service-deployer
spec:
  selector:
    app: service-deployer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
