# registry-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: kea-project
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
