# registry-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: kea-project
spec:
  storageClassName: yc-network-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
