@startuml
interface CacheInterface {
  {abstract} +GetToken(token: String, ssoToken: String): result_t
  {abstract} +SaveToken(token: SSOToken): result_t
}

class FakeCacheAdapter implements CacheInterface {
  -cache: map<String, String>
  +GetToken(token: String, ssoToken: String): result_t
  +SaveToken(token: SSOToken): result_t
}

interface ValidatorInterface {
  {abstract} +Validate(token: String): result_t
}

class SSOValidator implements ValidatorInterface {
  +Validate(token: String): result_t
}

class AuthenticationProvider {
  -cache: CacheInterface
  -validator: ValidatorInterface
  -rbacRules: String[]
  +SetRule(rule: String): result_t
  +GetRules(rules: String[]): result_t
  +Authenticate(token: String): result_t
  +ValidateToken(token: String): result_t
}

AuthenticationProvider --> CacheInterface
AuthenticationProvider --> ValidatorInterface
@enduml
