@startuml

actor "ML Engineer" as mlengineer

rectangle "Kubernetes" as K8s {
  usecase "Publish Model" as uc1
  rectangle "API Gateway" as System {
    usecase "Create instance of ML Service" as uc2
    usecase "Containerize Model with Docker" as uc3
    usecase "Create K8s Service" as uc4
  }
  
  rectangle "K8s Pod" as K8Pod {
  }
  
  rectangle "K8s Service" as K8Service {
  }
}

mlengineer -R-> uc1
uc1 <.R. uc2 : <<includes>>
uc3 -[hidden]-> uc2
uc1 <.R. uc3 : <<includes>>
uc1 <.R. uc4 : <<includes>>
uc4 -[hidden]U-> uc2
uc2 --> K8Pod
K8Service <-U- uc4

@enduml
