@startuml
actor "API Consumer" as consumer

rectangle "Kubernetes" as K8s {
  rectangle "K8s Service" as K8Service {
  }

  rectangle "API Gateway" as System {
    usecase "Send Request" as uc1
    usecase "Forward Request to K8s Service" as uc2
  }
}

consumer -R-> uc1
uc1 ..> uc2 : <<includes>>
uc2 --> K8Service

@enduml
