@startuml

actor "API Consumer" as consumer
actor "Security Specialist" as security

rectangle "API Gateway" as System {
  usecase "Send Request" as uc0
  usecase "Check Authorization Token" as uc1
  usecase "Redirect to SSO Login" as uc2
  usecase "Forward Authorized Request" as uc3
  usecase "Configure RBAC" as uc4
}

uc0 <-L- consumer
uc0 <.. uc1 : <<extends>>
uc1 --> uc2 : Token Invalid
uc1 --> uc3 : Token Valid
uc4 <-- security

@enduml
