@startuml

actor "API Consumer" as consumer

rectangle "API Gateway" as System {
  usecase "Send Request" as uc1
  usecase "Validate Request by OpenAPI schema" as uc2
}

consumer -R-> uc1
uc1 <.. uc2 : <<extends>>

@enduml
