@startuml

actor "ML Engineer" as mlengineer

rectangle "API Gateway" as System {
  usecase "Create instance of ML Service" as uc2
}

rectangle "Kubernetes" as K8s {
  usecase "Deploy Model" as uc1
  rectangle "K8s Pod" as K8Pod {
  }
}

mlengineer -R-> uc1
uc1 <.L. uc2 : <<includes>>
K8Pod <-U- uc2

@enduml
