@startuml
actor "ML Engineer" as mlengineer
actor "DevOps Engineer" as devops

usecase "Push Model to Repository" as uc1
usecase "Containerize Model with Docker" as uc2
usecase "Deploy Container to K8s Cluster" as uc3

mlengineer --> uc1
uc1 --> uc2
uc2 --> uc3
devops --> uc2
@enduml
