@startuml
class SmartHouse {
    -wall[4] : Wall
    -roof : Roof
    +stormWarning()
    +harden()
    +closeWindows()
}

class Wall {
}

class Roof {
    -frame : Frame
}

class Material {
    +price: double
    +unitWeight: double
}

SmartHouse --o Wall
SmartHouse --o Roof
Roof --> Frame

class Brick {
    +color: String {red,white}
}
Material <|-- Brick

class Plank {
    +type: String {oak,pine}
}
Material <|-- Plank

class Frame {
    - arr[0..40] : Plank
    - frameKind: FrameKind {triangleRoof,plainRoof,mansardRoof}
    - tilling : Tilling
}

class Tilling {
}
Material <|-- Tilling

Frame --> Plank
Wall --> Brick
Frame --> Tilling

@enduml
