@startuml

class "<<root>> Authentication Provider" as auth {
  +rbacRules: String[]
  +result_t Authenticate(token: String)
}

class "<<root>> SSO Provider" as sso {
  +cache: SSOToken[]
  +result_t ValidateToken(token: String)
}

class "<<entity>> SSO Token" as token {
  +token: String
  +login_time: DateTime
}

auth -- sso
sso "1" <-- "*" token

@enduml