@startuml

class "<<root>> Request Validator" as validator {
  +schema: OpenApiSchema
  +result_t Validate(request: Request)
}

class "<<entity>> OpenAPI Schema cached" as apischema {
  +id: String
  +data: JSON
}

class "<<value>> Request" as request {
  +id: int
  +data: string
}

validator "1" -- "1" apischema
validator "1" -- "1" request

@enduml