@startuml

class "<<root>> Response Cacher" as cacher {
  +cache: CacheEntry[]
  +result_t GetFromCache(request: Request, out response: Response)
  +result_t SetCache(request: Request, response: Response)
}

class "<<entity>> Cache Entry" as cache {
  +request_id: int
  +response: Response
}

class "<<value>> Request" as request {
  +id: int
  +data: string
}

class "<<value>> Response" as response {
  +id: int
  +data: string
}

cacher "1" <-- "*" cache
cacher -- request
cache -- response

@enduml