@startchen

entity Practice {
}

entity Lecture {
}

entity Topic {
}

entity Task <<weak>> {
}

relationship "Covers a" as LectureTopic {
}

relationship "Exercise a" as PracticeTask <<identifying>> {
}

relationship "Relates to" as TaskTopic {
}

Lecture -1- LectureTopic
LectureTopic -N- Topic

Practice -1- PracticeTask
PracticeTask =N= Task

Task -1- TaskTopic
TaskTopic -1- Topic

@endchen