@startuml
actor User

rectangle OnlineTranslator {
    usecase Translate as "Translate" <<abstract>>
    usecase TranslateWebPage as "Translate Web Page"
    usecase SetURL as "Set URL"
}

User --> Translate
Translate <-- TranslateWebPage
TranslateWebPage ..> SetURL : <<include>>
@enduml
