apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mldeployments.ml.kea-project.io
spec:
  group: ml.kea-project.io
  names:
    kind: MLDeployment
    listKind: MLDeploymentList
    plural: mldeployments
    singular: mldeployment
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                modelName:
                  type: string
                  description: "Name of the MLModel that this deployment references."
                replicas:
                  type: integer
                  description: "Number of pods in the deployment."
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
      additionalPrinterColumns:
        - name: ModelName
          type: string
          jsonPath: .spec.modelName
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
