apiVersion: ml.kea-project.io/v1alpha1
kind: MLDeployment
metadata:
  name: mymodel-deployment
  namespace: kea-project
spec:
  modelName: mymodel
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
