---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-app
  namespace: kea-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-app
  template:
    metadata:
      labels:
        app: ping-app
    spec:
      containers:
        - name: ping-app
          image: alpine/curl
          command: ["/bin/sh", "-c", "while true; do echo -e 'HTTP/1.1 200 OK\n\nPing!\n' | nc -l -p 80; done"]
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
  namespace: kea-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      containers:
        - name: pong-app
          image: alpine/curl
          command: ["/bin/sh", "-c", "while true; do echo -e 'HTTP/1.1 200 OK\n\n'$(curl --insecure http://ping-app-service.kea-project) | nc -l -p 80; done"]
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ping-app-service
  namespace: kea-project
spec:
  selector:
    app: ping-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pong-app-service
  namespace: kea-project
spec:
  selector:
    app: pong-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: kea-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /kea-project/ping
            pathType: Prefix
            backend:
              service:
                name: ping-app-service
                port:
                  number: 80
          - path: /kea-project/pong
            pathType: Prefix
            backend:
              service:
                name: pong-app-service
                port:
                  number: 80
