@startchen

entity Teacher {
}

entity Lecture {
}

entity Practice {
}

relationship "Lecturer at" as LecturerAt {
}

relationship "Assistant at" as AssistantrAt {
}

Teacher -N- LecturerAt
LecturerAt -M- Lecture

Teacher -N- AssistantrAt
AssistantrAt -M- Practice

@endchen