@startuml

class Person {
  +FullName: String
}

class Company {}

class Address {
  +street: String
  +city: String
  +building: Integer {positive}
}

Person : owner
Person --> Address : registeredAt
Person --> Address : actual

Company --> Address : legalAddress
Company --> Address : postAddress

@enduml
